// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: api/captcha/captcha.proto

package captcha

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通过purpose字段限制用途
type Purpose int32

const (
	// shor message code
	Purpose_SIGN_UP      Purpose = 0
	Purpose_RESET_PASSWD Purpose = 1
	// graph captcha
	Purpose_SIGN_IN Purpose = 2
)

// Enum value maps for Purpose.
var (
	Purpose_name = map[int32]string{
		0: "SIGN_UP",
		1: "RESET_PASSWD",
		2: "SIGN_IN",
	}
	Purpose_value = map[string]int32{
		"SIGN_UP":      0,
		"RESET_PASSWD": 1,
		"SIGN_IN":      2,
	}
)

func (x Purpose) Enum() *Purpose {
	p := new(Purpose)
	*p = x
	return p
}

func (x Purpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Purpose) Descriptor() protoreflect.EnumDescriptor {
	return file_api_captcha_captcha_proto_enumTypes[0].Descriptor()
}

func (Purpose) Type() protoreflect.EnumType {
	return &file_api_captcha_captcha_proto_enumTypes[0]
}

func (x Purpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Purpose.Descriptor instead.
func (Purpose) EnumDescriptor() ([]byte, []int) {
	return file_api_captcha_captcha_proto_rawDescGZIP(), []int{0}
}

type Captcha struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Purpose  Purpose `protobuf:"varint,2,opt,name=purpose,proto3,enum=captcha.Purpose" json:"purpose,omitempty"`
	Content  string  `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Message  string  `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Deadline int64   `protobuf:"varint,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
}

func (x *Captcha) Reset() {
	*x = Captcha{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_captcha_captcha_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Captcha) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Captcha) ProtoMessage() {}

func (x *Captcha) ProtoReflect() protoreflect.Message {
	mi := &file_api_captcha_captcha_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Captcha.ProtoReflect.Descriptor instead.
func (*Captcha) Descriptor() ([]byte, []int) {
	return file_api_captcha_captcha_proto_rawDescGZIP(), []int{0}
}

func (x *Captcha) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Captcha) GetPurpose() Purpose {
	if x != nil {
		return x.Purpose
	}
	return Purpose_SIGN_UP
}

func (x *Captcha) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Captcha) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Captcha) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

type SignUpCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Account:
	//	*SignUpCodeReq_Email
	//	*SignUpCodeReq_PhoneNumber
	Account isSignUpCodeReq_Account `protobuf_oneof:"account"`
	Purpose Purpose                 `protobuf:"varint,3,opt,name=purpose,proto3,enum=captcha.Purpose" json:"purpose,omitempty"`
}

func (x *SignUpCodeReq) Reset() {
	*x = SignUpCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_captcha_captcha_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpCodeReq) ProtoMessage() {}

func (x *SignUpCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_captcha_captcha_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpCodeReq.ProtoReflect.Descriptor instead.
func (*SignUpCodeReq) Descriptor() ([]byte, []int) {
	return file_api_captcha_captcha_proto_rawDescGZIP(), []int{1}
}

func (m *SignUpCodeReq) GetAccount() isSignUpCodeReq_Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (x *SignUpCodeReq) GetEmail() string {
	if x, ok := x.GetAccount().(*SignUpCodeReq_Email); ok {
		return x.Email
	}
	return ""
}

func (x *SignUpCodeReq) GetPhoneNumber() string {
	if x, ok := x.GetAccount().(*SignUpCodeReq_PhoneNumber); ok {
		return x.PhoneNumber
	}
	return ""
}

func (x *SignUpCodeReq) GetPurpose() Purpose {
	if x != nil {
		return x.Purpose
	}
	return Purpose_SIGN_UP
}

type isSignUpCodeReq_Account interface {
	isSignUpCodeReq_Account()
}

type SignUpCodeReq_Email struct {
	Email string `protobuf:"bytes,1,opt,name=email,proto3,oneof"`
}

type SignUpCodeReq_PhoneNumber struct {
	PhoneNumber string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3,oneof"`
}

func (*SignUpCodeReq_Email) isSignUpCodeReq_Account() {}

func (*SignUpCodeReq_PhoneNumber) isSignUpCodeReq_Account() {}

type SignUpCodeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SignUpCodeRsp) Reset() {
	*x = SignUpCodeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_captcha_captcha_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpCodeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpCodeRsp) ProtoMessage() {}

func (x *SignUpCodeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_captcha_captcha_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpCodeRsp.ProtoReflect.Descriptor instead.
func (*SignUpCodeRsp) Descriptor() ([]byte, []int) {
	return file_api_captcha_captcha_proto_rawDescGZIP(), []int{2}
}

func (x *SignUpCodeRsp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GraphCaptchaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Purpose Purpose `protobuf:"varint,3,opt,name=purpose,proto3,enum=captcha.Purpose" json:"purpose,omitempty"`
}

func (x *GraphCaptchaReq) Reset() {
	*x = GraphCaptchaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_captcha_captcha_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphCaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphCaptchaReq) ProtoMessage() {}

func (x *GraphCaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_captcha_captcha_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphCaptchaReq.ProtoReflect.Descriptor instead.
func (*GraphCaptchaReq) Descriptor() ([]byte, []int) {
	return file_api_captcha_captcha_proto_rawDescGZIP(), []int{3}
}

func (x *GraphCaptchaReq) GetPurpose() Purpose {
	if x != nil {
		return x.Purpose
	}
	return Purpose_SIGN_UP
}

type GraphCaptchaRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Captcha *Captcha `protobuf:"bytes,1,opt,name=captcha,proto3" json:"captcha,omitempty"`
}

func (x *GraphCaptchaRsp) Reset() {
	*x = GraphCaptchaRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_captcha_captcha_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphCaptchaRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphCaptchaRsp) ProtoMessage() {}

func (x *GraphCaptchaRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_captcha_captcha_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphCaptchaRsp.ProtoReflect.Descriptor instead.
func (*GraphCaptchaRsp) Descriptor() ([]byte, []int) {
	return file_api_captcha_captcha_proto_rawDescGZIP(), []int{4}
}

func (x *GraphCaptchaRsp) GetCaptcha() *Captcha {
	if x != nil {
		return x.Captcha
	}
	return nil
}

type VerifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value   string  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Purpose Purpose `protobuf:"varint,3,opt,name=purpose,proto3,enum=captcha.Purpose" json:"purpose,omitempty"`
}

func (x *VerifyReq) Reset() {
	*x = VerifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_captcha_captcha_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyReq) ProtoMessage() {}

func (x *VerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_captcha_captcha_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyReq.ProtoReflect.Descriptor instead.
func (*VerifyReq) Descriptor() ([]byte, []int) {
	return file_api_captcha_captcha_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VerifyReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *VerifyReq) GetPurpose() Purpose {
	if x != nil {
		return x.Purpose
	}
	return Purpose_SIGN_UP
}

type VerifyRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *VerifyRsp) Reset() {
	*x = VerifyRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_captcha_captcha_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRsp) ProtoMessage() {}

func (x *VerifyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_captcha_captcha_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRsp.ProtoReflect.Descriptor instead.
func (*VerifyRsp) Descriptor() ([]byte, []int) {
	return file_api_captcha_captcha_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyRsp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_captcha_captcha_proto protoreflect.FileDescriptor

var file_api_captcha_captcha_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2f, 0x63, 0x61,
	0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x61, 0x70,
	0x74, 0x63, 0x68, 0x61, 0x22, 0x97, 0x01, 0x0a, 0x07, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x50, 0x75,
	0x72, 0x70, 0x6f, 0x73, 0x65, 0x52, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x83,
	0x01, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x23, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2a, 0x0a,
	0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x50, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65,
	0x52, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x29, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x3d, 0x0a, 0x0f, 0x47, 0x72, 0x61, 0x70, 0x68, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52,
	0x65, 0x71, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x50, 0x75,
	0x72, 0x70, 0x6f, 0x73, 0x65, 0x52, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x22, 0x3d,
	0x0a, 0x0f, 0x47, 0x72, 0x61, 0x70, 0x68, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x73,
	0x70, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x43, 0x61, 0x70,
	0x74, 0x63, 0x68, 0x61, 0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x22, 0x5f, 0x0a,
	0x09, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x50, 0x75,
	0x72, 0x70, 0x6f, 0x73, 0x65, 0x52, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x22, 0x25,
	0x0a, 0x09, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x2a, 0x35, 0x0a, 0x07, 0x50, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x49, 0x47, 0x4e, 0x5f, 0x55, 0x50, 0x10, 0x00, 0x12, 0x10, 0x0a,
	0x0c, 0x52, 0x45, 0x53, 0x45, 0x54, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x44, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x49, 0x47, 0x4e, 0x5f, 0x49, 0x4e, 0x10, 0x02, 0x32, 0xc4, 0x01, 0x0a,
	0x0e, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3c, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x2e,
	0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e,
	0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x73, 0x70, 0x12, 0x42, 0x0a,
	0x0c, 0x47, 0x72, 0x61, 0x70, 0x68, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x12, 0x18, 0x2e,
	0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x43, 0x61, 0x70,
	0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68,
	0x61, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x73,
	0x70, 0x12, 0x30, 0x0a, 0x06, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x12, 0x2e, 0x63, 0x61,
	0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x12, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x52, 0x73, 0x70, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x79, 0x7a, 0x6a, 0x2f, 0x67, 0x72, 0x69, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_captcha_captcha_proto_rawDescOnce sync.Once
	file_api_captcha_captcha_proto_rawDescData = file_api_captcha_captcha_proto_rawDesc
)

func file_api_captcha_captcha_proto_rawDescGZIP() []byte {
	file_api_captcha_captcha_proto_rawDescOnce.Do(func() {
		file_api_captcha_captcha_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_captcha_captcha_proto_rawDescData)
	})
	return file_api_captcha_captcha_proto_rawDescData
}

var file_api_captcha_captcha_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_captcha_captcha_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_captcha_captcha_proto_goTypes = []interface{}{
	(Purpose)(0),            // 0: captcha.Purpose
	(*Captcha)(nil),         // 1: captcha.Captcha
	(*SignUpCodeReq)(nil),   // 2: captcha.SignUpCodeReq
	(*SignUpCodeRsp)(nil),   // 3: captcha.SignUpCodeRsp
	(*GraphCaptchaReq)(nil), // 4: captcha.GraphCaptchaReq
	(*GraphCaptchaRsp)(nil), // 5: captcha.GraphCaptchaRsp
	(*VerifyReq)(nil),       // 6: captcha.VerifyReq
	(*VerifyRsp)(nil),       // 7: captcha.VerifyRsp
}
var file_api_captcha_captcha_proto_depIdxs = []int32{
	0, // 0: captcha.Captcha.purpose:type_name -> captcha.Purpose
	0, // 1: captcha.SignUpCodeReq.purpose:type_name -> captcha.Purpose
	0, // 2: captcha.GraphCaptchaReq.purpose:type_name -> captcha.Purpose
	1, // 3: captcha.GraphCaptchaRsp.captcha:type_name -> captcha.Captcha
	0, // 4: captcha.VerifyReq.purpose:type_name -> captcha.Purpose
	2, // 5: captcha.CaptchaService.SignUpCode:input_type -> captcha.SignUpCodeReq
	4, // 6: captcha.CaptchaService.GraphCaptcha:input_type -> captcha.GraphCaptchaReq
	6, // 7: captcha.CaptchaService.Verify:input_type -> captcha.VerifyReq
	3, // 8: captcha.CaptchaService.SignUpCode:output_type -> captcha.SignUpCodeRsp
	5, // 9: captcha.CaptchaService.GraphCaptcha:output_type -> captcha.GraphCaptchaRsp
	7, // 10: captcha.CaptchaService.Verify:output_type -> captcha.VerifyRsp
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_captcha_captcha_proto_init() }
func file_api_captcha_captcha_proto_init() {
	if File_api_captcha_captcha_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_captcha_captcha_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Captcha); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_captcha_captcha_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_captcha_captcha_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpCodeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_captcha_captcha_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphCaptchaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_captcha_captcha_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphCaptchaRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_captcha_captcha_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_captcha_captcha_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_captcha_captcha_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SignUpCodeReq_Email)(nil),
		(*SignUpCodeReq_PhoneNumber)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_captcha_captcha_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_captcha_captcha_proto_goTypes,
		DependencyIndexes: file_api_captcha_captcha_proto_depIdxs,
		EnumInfos:         file_api_captcha_captcha_proto_enumTypes,
		MessageInfos:      file_api_captcha_captcha_proto_msgTypes,
	}.Build()
	File_api_captcha_captcha_proto = out.File
	file_api_captcha_captcha_proto_rawDesc = nil
	file_api_captcha_captcha_proto_goTypes = nil
	file_api_captcha_captcha_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CaptchaServiceClient is the client API for CaptchaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CaptchaServiceClient interface {
	// 短信验证码
	SignUpCode(ctx context.Context, in *SignUpCodeReq, opts ...grpc.CallOption) (*SignUpCodeRsp, error)
	// 图形验证码
	GraphCaptcha(ctx context.Context, in *GraphCaptchaReq, opts ...grpc.CallOption) (*GraphCaptchaRsp, error)
	// 验证码校验
	Verify(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*VerifyRsp, error)
}

type captchaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCaptchaServiceClient(cc grpc.ClientConnInterface) CaptchaServiceClient {
	return &captchaServiceClient{cc}
}

func (c *captchaServiceClient) SignUpCode(ctx context.Context, in *SignUpCodeReq, opts ...grpc.CallOption) (*SignUpCodeRsp, error) {
	out := new(SignUpCodeRsp)
	err := c.cc.Invoke(ctx, "/captcha.CaptchaService/SignUpCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captchaServiceClient) GraphCaptcha(ctx context.Context, in *GraphCaptchaReq, opts ...grpc.CallOption) (*GraphCaptchaRsp, error) {
	out := new(GraphCaptchaRsp)
	err := c.cc.Invoke(ctx, "/captcha.CaptchaService/GraphCaptcha", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captchaServiceClient) Verify(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*VerifyRsp, error) {
	out := new(VerifyRsp)
	err := c.cc.Invoke(ctx, "/captcha.CaptchaService/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaptchaServiceServer is the server API for CaptchaService service.
type CaptchaServiceServer interface {
	// 短信验证码
	SignUpCode(context.Context, *SignUpCodeReq) (*SignUpCodeRsp, error)
	// 图形验证码
	GraphCaptcha(context.Context, *GraphCaptchaReq) (*GraphCaptchaRsp, error)
	// 验证码校验
	Verify(context.Context, *VerifyReq) (*VerifyRsp, error)
}

// UnimplementedCaptchaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCaptchaServiceServer struct {
}

func (*UnimplementedCaptchaServiceServer) SignUpCode(context.Context, *SignUpCodeReq) (*SignUpCodeRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUpCode not implemented")
}
func (*UnimplementedCaptchaServiceServer) GraphCaptcha(context.Context, *GraphCaptchaReq) (*GraphCaptchaRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GraphCaptcha not implemented")
}
func (*UnimplementedCaptchaServiceServer) Verify(context.Context, *VerifyReq) (*VerifyRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}

func RegisterCaptchaServiceServer(s *grpc.Server, srv CaptchaServiceServer) {
	s.RegisterService(&_CaptchaService_serviceDesc, srv)
}

func _CaptchaService_SignUpCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptchaServiceServer).SignUpCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/captcha.CaptchaService/SignUpCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptchaServiceServer).SignUpCode(ctx, req.(*SignUpCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptchaService_GraphCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphCaptchaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptchaServiceServer).GraphCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/captcha.CaptchaService/GraphCaptcha",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptchaServiceServer).GraphCaptcha(ctx, req.(*GraphCaptchaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptchaService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptchaServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/captcha.CaptchaService/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptchaServiceServer).Verify(ctx, req.(*VerifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CaptchaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "captcha.CaptchaService",
	HandlerType: (*CaptchaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUpCode",
			Handler:    _CaptchaService_SignUpCode_Handler,
		},
		{
			MethodName: "GraphCaptcha",
			Handler:    _CaptchaService_GraphCaptcha_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _CaptchaService_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/captcha/captcha.proto",
}
