// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/auth/user.proto

package auth

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Account              string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Username             string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string                 `protobuf:"bytes,5,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64                  `protobuf:"varint,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_73666f97dd6435b8, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "grin.api.auth.User")
}

func init() { proto.RegisterFile("api/auth/user.proto", fileDescriptor_73666f97dd6435b8) }

var fileDescriptor_73666f97dd6435b8 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4e, 0x84, 0x30,
	0x14, 0x45, 0x53, 0x86, 0x61, 0xe4, 0x4d, 0x74, 0x51, 0x5d, 0x34, 0xc4, 0x44, 0xe2, 0x8a, 0x55,
	0x49, 0x74, 0xe3, 0x56, 0x3f, 0xc0, 0x05, 0xd1, 0x8d, 0xbb, 0x07, 0x3c, 0x99, 0x26, 0x53, 0xda,
	0x94, 0xf6, 0x6f, 0xfd, 0x18, 0x43, 0x11, 0x99, 0xe5, 0xbd, 0xe7, 0xb6, 0x3d, 0x29, 0xdc, 0xa2,
	0x55, 0x35, 0x06, 0x7f, 0xaa, 0xc3, 0x44, 0x4e, 0x5a, 0x67, 0xbc, 0xe1, 0xd7, 0x83, 0x53, 0xa3,
	0x44, 0xab, 0xe4, 0x4c, 0x8a, 0x87, 0xc1, 0x98, 0xe1, 0x4c, 0x75, 0x84, 0x6d, 0xf8, 0xae, 0xbd,
	0xd2, 0x34, 0x79, 0xd4, 0x76, 0xd9, 0x3f, 0xfe, 0x30, 0x48, 0x3f, 0x27, 0x72, 0xfc, 0x06, 0x12,
	0xd5, 0x0b, 0x56, 0xb2, 0x6a, 0xd7, 0x24, 0xaa, 0xe7, 0x02, 0x0e, 0xd8, 0x75, 0x26, 0x8c, 0x5e,
	0x24, 0x25, 0xab, 0xf2, 0x66, 0x8d, 0xbc, 0x80, 0xab, 0xf9, 0xc1, 0x11, 0x35, 0x89, 0x5d, 0x44,
	0xff, 0x99, 0xdf, 0xc1, 0x9e, 0x34, 0xaa, 0xb3, 0x48, 0x23, 0x58, 0x02, 0x2f, 0xe1, 0x68, 0x4f,
	0x66, 0xa4, 0xf7, 0xa0, 0x5b, 0x72, 0x62, 0x1f, 0xd9, 0x65, 0xc5, 0x5f, 0x20, 0xef, 0x1c, 0xa1,
	0xa7, 0xfe, 0xd5, 0x8b, 0xac, 0x64, 0xd5, 0xf1, 0xa9, 0x90, 0x8b, 0xbb, 0x5c, 0xdd, 0xe5, 0xc7,
	0xea, 0xde, 0x6c, 0x63, 0x7e, 0x0f, 0x79, 0xb0, 0xfd, 0xdf, 0xc9, 0x43, 0xd4, 0xdf, 0x8a, 0xb7,
	0xec, 0x2b, 0x9d, 0xff, 0xa1, 0xcd, 0xe2, 0x25, 0xcf, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x46,
	0x97, 0x44, 0xa5, 0x34, 0x01, 0x00, 0x00,
}
